<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\DateRuleAction;
use App\Enums\DateRuleCondition;
use App\Enums\DateRuleOperation;
use App\Enums\DateRuleType;
use App\Models\DateValidationRule;
use Illuminate\Database\Seeder;

final class DateValidationRuleSeeder extends Seeder
{
    public function run(): void
    {
        /** @var array<int, array<string, mixed>> $rules */
        $rules = [
            [
                'nombre' => 'GLOBAL_TODOS_LOS_CAMPOS_FECHA_VALIDOS',
                'descripcion' => 'Regla global: cualquier campo de fecha modificado debe contener una fecha valida.',
                'tabla1' => '*',
                'tabla2' => null,
                'campo1' => '*',
                'campo2' => null,
                'condicion' => DateRuleCondition::IS_DATE,
                'mensaje' => 'El valor introducido debe tener un formato de fecha valido.',
                'mensaje_preventivo' => null,
                'mensaje_cumplida' => 'El campo tiene un valor de fecha valido.',
                'mensaje_incumplida' => 'El campo no contiene una fecha valida. Revise el formato.',
                'tipo' => DateRuleType::ERROR,
                'fase' => null,
                'estado' => null,
                'accion' => DateRuleAction::NONE,
                'activa' => true,
                'operacion' => DateRuleOperation::BOTH,
                'plazo_dias' => null,
                'aviso_dias' => null,
                'connection_name' => 'Obras',
                'dispara_si_cumple' => false,
            ],
            [
                'nombre' => 'GLOBAL_FECHA_DEBE_SER_POSTERIOR_A_HOY',
                'descripcion' => 'Regla global: cualquier fecha modificada debe ser posterior al dia actual.',
                'tabla1' => '*',
                'tabla2' => null,
                'campo1' => '*',
                'campo2' => null,
                'condicion' => DateRuleCondition::AFTER_TODAY,
                'mensaje' => 'La fecha debe ser posterior a la fecha actual.',
                'mensaje_preventivo' => null,
                'mensaje_cumplida' => 'La fecha es posterior al dia actual.',
                'mensaje_incumplida' => 'La fecha indicada no es posterior al dia actual.',
                'tipo' => DateRuleType::ERROR,
                'fase' => null,
                'estado' => null,
                'accion' => DateRuleAction::NONE,
                'activa' => true,
                'operacion' => DateRuleOperation::BOTH,
                'plazo_dias' => null,
                'aviso_dias' => null,
                'connection_name' => 'Obras',
                'dispara_si_cumple' => false,
            ],
            [
                'nombre' => 'GLOBAL_FECHA_DEBE_SER_POSTERIOR_O_IGUAL_A_HOY',
                'descripcion' => 'Plantilla global: cualquier fecha modificada debe ser posterior o igual al dia actual.',
                'tabla1' => '*',
                'tabla2' => null,
                'campo1' => '*',
                'campo2' => null,
                'condicion' => DateRuleCondition::AFTER_OR_EQUAL_TODAY,
                'mensaje' => 'La fecha debe ser posterior o igual a la fecha actual.',
                'mensaje_preventivo' => null,
                'mensaje_cumplida' => 'La fecha es posterior o igual al dia actual.',
                'mensaje_incumplida' => 'La fecha indicada es anterior al dia actual.',
                'tipo' => DateRuleType::ERROR,
                'fase' => null,
                'estado' => null,
                'accion' => DateRuleAction::NONE,
                'activa' => false,
                'operacion' => DateRuleOperation::BOTH,
                'plazo_dias' => null,
                'aviso_dias' => null,
                'connection_name' => 'Obras',
                'dispara_si_cumple' => false,
            ],
            [
                'nombre' => 'GLOBAL_FECHA_DEBE_SER_ANTERIOR_O_IGUAL_A_HOY',
                'descripcion' => 'Plantilla global: cualquier fecha modificada debe ser anterior o igual al dia actual.',
                'tabla1' => '*',
                'tabla2' => null,
                'campo1' => '*',
                'campo2' => null,
                'condicion' => DateRuleCondition::BEFORE_OR_EQUAL_TODAY,
                'mensaje' => 'La fecha debe ser anterior o igual a la fecha actual.',
                'mensaje_preventivo' => null,
                'mensaje_cumplida' => 'La fecha es anterior o igual al dia actual.',
                'mensaje_incumplida' => 'La fecha indicada es posterior al dia actual.',
                'tipo' => DateRuleType::ERROR,
                'fase' => null,
                'estado' => null,
                'accion' => DateRuleAction::NONE,
                'activa' => false,
                'operacion' => DateRuleOperation::BOTH,
                'plazo_dias' => null,
                'aviso_dias' => null,
                'connection_name' => 'Obras',
                'dispara_si_cumple' => false,
            ],
            [
                'nombre' => 'INICIO_PETICION_AR_ANTES_INICIO_AR',
                'descripcion' => 'La peticion del acta de replanteo previo no debe quedar despues del inicio del acta de replanteo.',
                'tabla1' => 'DatosInicioDeObras',
                'tabla2' => 'ActasDeReplanteo',
                'campo1' => 'fecha_pet_acta_replanteo',
                'campo2' => 'Fecha_Inicio_Acta_Replanteo',
                'condicion' => DateRuleCondition::BEFORE_OR_EQUAL,
                'mensaje' => 'La peticion del acta de replanteo debe registrarse antes o el mismo dia del inicio del acta.',
                'mensaje_preventivo' => null,
                'mensaje_cumplida' => 'La peticion del acta de replanteo previo esta registrada en orden temporal correcto.',
                'mensaje_incumplida' => 'La peticion del acta de replanteo previo figura despues del inicio del acta. Revise las fechas.',
                'tipo' => DateRuleType::ERROR,
                'fase' => null,
                'estado' => null,
                'accion' => DateRuleAction::NONE,
                'activa' => true,
                'operacion' => DateRuleOperation::BOTH,
                'plazo_dias' => null,
                'aviso_dias' => null,
                'connection_name' => 'Obras',
                'dispara_si_cumple' => false,
            ],
            [
                'nombre' => 'AR_INICIO_ANTES_FIN',
                'descripcion' => 'El inicio del acta de replanteo debe ser anterior o igual a su fecha final.',
                'tabla1' => 'ActasDeReplanteo',
                'tabla2' => 'ActasDeReplanteo',
                'campo1' => 'Fecha_Inicio_Acta_Replanteo',
                'campo2' => 'Fecha_Final_Acta_Replanteo',
                'condicion' => DateRuleCondition::BEFORE_OR_EQUAL,
                'mensaje' => 'La fecha de inicio del acta de replanteo no puede ser posterior a la fecha final.',
                'mensaje_preventivo' => null,
                'mensaje_cumplida' => 'El acta de replanteo mantiene coherencia entre fecha de inicio y fecha final.',
                'mensaje_incumplida' => 'La fecha final del acta de replanteo es anterior a su fecha de inicio.',
                'tipo' => DateRuleType::ERROR,
                'fase' => null,
                'estado' => null,
                'accion' => DateRuleAction::NONE,
                'activa' => true,
                'operacion' => DateRuleOperation::BOTH,
                'plazo_dias' => null,
                'aviso_dias' => null,
                'connection_name' => 'Obras',
                'dispara_si_cumple' => false,
            ],
            [
                'nombre' => 'RECEPCION_PROVISIONAL_ANTES_DEFINITIVA',
                'descripcion' => 'La recepcion provisional debe quedar antes o el mismo dia que la recepcion definitiva.',
                'tabla1' => 'ActasRecepcionObra',
                'tabla2' => 'ActasRecepcionObra',
                'campo1' => 'Fecha_Acta_RecProv',
                'campo2' => 'Fecha_Acta_Rec',
                'condicion' => DateRuleCondition::BEFORE_OR_EQUAL,
                'mensaje' => 'La recepcion provisional debe producirse antes o el mismo dia que la recepcion definitiva.',
                'mensaje_preventivo' => null,
                'mensaje_cumplida' => 'Las fechas de recepcion provisional y definitiva estan en orden correcto.',
                'mensaje_incumplida' => 'La recepcion provisional figura despues de la recepcion definitiva. Revise el expediente.',
                'tipo' => DateRuleType::ERROR,
                'fase' => null,
                'estado' => null,
                'accion' => DateRuleAction::NONE,
                'activa' => true,
                'operacion' => DateRuleOperation::BOTH,
                'plazo_dias' => null,
                'aviso_dias' => null,
                'connection_name' => 'Obras',
                'dispara_si_cumple' => false,
            ],
            [
                'nombre' => 'PROYECTO_ENTREGA_ANTES_RECEPCION',
                'descripcion' => 'La entrega de proyecto debe quedar registrada antes o el mismo dia que su recepcion.',
                'tabla1' => 'Proyectos',
                'tabla2' => 'Proyectos',
                'campo1' => 'fecha_entrega_proyecto',
                'campo2' => 'fecha_recepcion_proyecto',
                'condicion' => DateRuleCondition::BEFORE_OR_EQUAL,
                'mensaje' => 'La fecha de entrega del proyecto no puede ser posterior a la fecha de recepcion.',
                'mensaje_preventivo' => null,
                'mensaje_cumplida' => 'La secuencia entrega-recepcion del proyecto es correcta.',
                'mensaje_incumplida' => 'La fecha de entrega del proyecto aparece despues de su recepcion.',
                'tipo' => DateRuleType::WARNING,
                'fase' => null,
                'estado' => null,
                'accion' => DateRuleAction::NONE,
                'activa' => true,
                'operacion' => DateRuleOperation::BOTH,
                'plazo_dias' => null,
                'aviso_dias' => null,
                'connection_name' => 'Obras',
                'dispara_si_cumple' => false,
            ],
            [
                'nombre' => 'PROYECTO_REMISION_ANTES_APROBACION',
                'descripcion' => 'La remision del proyecto al ayuntamiento debe quedar antes o el mismo dia que su aprobacion.',
                'tabla1' => 'Proyectos',
                'tabla2' => 'Proyectos',
                'campo1' => 'fecha_remision_ayto',
                'campo2' => 'fecha_aprobacion_ayto',
                'condicion' => DateRuleCondition::BEFORE_OR_EQUAL,
                'mensaje' => 'La remision del proyecto al ayuntamiento no puede registrarse despues de su aprobacion.',
                'mensaje_preventivo' => null,
                'mensaje_cumplida' => 'La remision y la aprobacion del proyecto por el ayuntamiento mantienen el orden esperado.',
                'mensaje_incumplida' => 'La aprobacion del proyecto figura antes de la remision al ayuntamiento.',
                'tipo' => DateRuleType::WARNING,
                'fase' => null,
                'estado' => null,
                'accion' => DateRuleAction::NONE,
                'activa' => true,
                'operacion' => DateRuleOperation::BOTH,
                'plazo_dias' => null,
                'aviso_dias' => null,
                'connection_name' => 'Obras',
                'dispara_si_cumple' => false,
            ],
            [
                'nombre' => 'CESION_REMISION_ANTES_CESION',
                'descripcion' => 'La remision al ayuntamiento previa a la cesion debe existir antes o el mismo dia que la fecha de cesion.',
                'tabla1' => 'ObrasCedidas',
                'tabla2' => 'ObrasCedidas',
                'campo1' => 'FechaRemisionAyto',
                'campo2' => 'FechaCesion',
                'condicion' => DateRuleCondition::BEFORE_OR_EQUAL,
                'mensaje' => 'La remision al ayuntamiento debe quedar antes o el mismo dia que la cesion.',
                'mensaje_preventivo' => null,
                'mensaje_cumplida' => 'La documentacion de cesion mantiene la secuencia remision-cesion.',
                'mensaje_incumplida' => 'La fecha de cesion aparece antes de la remision al ayuntamiento.',
                'tipo' => DateRuleType::WARNING,
                'fase' => null,
                'estado' => null,
                'accion' => DateRuleAction::NONE,
                'activa' => true,
                'operacion' => DateRuleOperation::BOTH,
                'plazo_dias' => null,
                'aviso_dias' => null,
                'connection_name' => 'Obras',
                'dispara_si_cumple' => false,
            ],
            [
                'nombre' => 'DOC_POSTERIOR_A_REPLANTEO',
                'descripcion' => 'La fecha de incorporacion del documento debe ser posterior o igual al inicio del acta de replanteo.',
                'tabla1' => 'dbo.documentacionexpedientes',
                'tabla2' => 'ActasDeReplanteo',
                'campo1' => 'fechaincorporacion',
                'campo2' => 'Fecha_Inicio_Acta_Replanteo',
                'condicion' => DateRuleCondition::AFTER_OR_EQUAL,
                'mensaje' => 'La fecha del documento no puede ser anterior al acta de replanteo.',
                'mensaje_preventivo' => null,
                'mensaje_cumplida' => 'El documento se incorporo con una fecha posterior o igual al inicio del acta de replanteo.',
                'mensaje_incumplida' => 'El documento figura incorporado antes del inicio del acta de replanteo.',
                'tipo' => DateRuleType::ERROR,
                'fase' => null,
                'estado' => null,
                'accion' => DateRuleAction::NONE,
                'activa' => true,
                'operacion' => DateRuleOperation::BOTH,
                'plazo_dias' => null,
                'aviso_dias' => null,
                'connection_name' => 'Obras',
                'dispara_si_cumple' => false,
            ],
            [
                'nombre' => 'DOC_MAX_30_DIAS_DESDE_REPLANTEO',
                'descripcion' => 'El documento debe incorporarse en un maximo de 30 dias desde el inicio del acta de replanteo.',
                'tabla1' => 'dbo.documentacionexpedientes',
                'tabla2' => 'ActasDeReplanteo',
                'campo1' => 'fechaincorporacion',
                'campo2' => 'Fecha_Inicio_Acta_Replanteo',
                'condicion' => DateRuleCondition::MAX_DAYS_BETWEEN,
                'mensaje' => 'Se ha superado el plazo de 30 dias para incorporar este documento.',
                'mensaje_preventivo' => null,
                'mensaje_cumplida' => 'El documento se incorporo dentro del plazo maximo de 30 dias.',
                'mensaje_incumplida' => 'Han pasado mas de 30 dias entre el inicio del acta de replanteo y la incorporacion del documento.',
                'tipo' => DateRuleType::WARNING,
                'fase' => null,
                'estado' => null,
                'accion' => DateRuleAction::NONE,
                'activa' => true,
                'operacion' => DateRuleOperation::BOTH,
                'plazo_dias' => 30,
                'aviso_dias' => null,
                'connection_name' => 'Obras',
                'dispara_si_cumple' => false,
            ],
            [
                'nombre' => 'EXPEDIENTE_PLAZO_REPLANTEO_NO_VENCIDO',
                'descripcion' => 'Controla que no haya vencido el plazo general de 180 dias desde la fecha de inicio del acta de replanteo.',
                'tabla1' => 'ActasDeReplanteo',
                'tabla2' => null,
                'campo1' => 'Fecha_Inicio_Acta_Replanteo',
                'campo2' => null,
                'condicion' => DateRuleCondition::DEADLINE_NOT_EXPIRED,
                'mensaje' => 'El plazo general del expediente esta vencido.',
                'mensaje_preventivo' => 'El plazo general del expediente esta cerca de vencer. Revise las actuaciones pendientes.',
                'mensaje_cumplida' => 'El expediente sigue dentro del plazo general de tramitacion asociado al replanteo.',
                'mensaje_incumplida' => 'El plazo general del expediente ya ha vencido desde la fecha de replanteo.',
                'tipo' => DateRuleType::WARNING,
                'fase' => null,
                'estado' => null,
                'accion' => DateRuleAction::NONE,
                'activa' => true,
                'operacion' => DateRuleOperation::BOTH,
                'plazo_dias' => 180,
                'aviso_dias' => null,
                'connection_name' => 'Obras',
                'dispara_si_cumple' => false,
            ],
            [
                'nombre' => 'EXPEDIENTE_AVISO_15_DIAS_FIN_PLAZO',
                'descripcion' => 'Notifica al team del expediente cuando faltan 15 dias o menos para vencer el plazo general.',
                'tabla1' => 'ActasDeReplanteo',
                'tabla2' => null,
                'campo1' => 'Fecha_Inicio_Acta_Replanteo',
                'campo2' => null,
                'condicion' => DateRuleCondition::DAYS_TO_DEADLINE_LTE,
                'mensaje' => 'Quedan 15 dias o menos para el vencimiento del expediente.',
                'mensaje_preventivo' => 'Quedan 15 dias o menos para que venza el plazo general del expediente. Conviene revisar tareas y documentacion pendiente.',
                'mensaje_cumplida' => 'El expediente ha entrado en la ventana de preaviso configurada para su vencimiento.',
                'mensaje_incumplida' => 'El expediente aun no ha entrado en la ventana de preaviso.',
                'tipo' => DateRuleType::NOTIFICATION,
                'fase' => null,
                'estado' => null,
                'accion' => DateRuleAction::NOTIFY,
                'activa' => true,
                'operacion' => DateRuleOperation::BOTH,
                'plazo_dias' => 180,
                'aviso_dias' => 15,
                'connection_name' => 'Obras',
                'dispara_si_cumple' => true,
            ],
            [
                'nombre' => 'PROYECTO_RECEPCION_REGISTRADA',
                'descripcion' => 'Lanza una notificacion cuando ya consta fecha de recepcion de proyecto.',
                'tabla1' => 'Proyectos',
                'tabla2' => null,
                'campo1' => 'fecha_recepcion_proyecto',
                'campo2' => null,
                'condicion' => DateRuleCondition::IS_DATE,
                'mensaje' => 'La recepcion del proyecto ha quedado registrada.',
                'mensaje_preventivo' => null,
                'mensaje_cumplida' => 'Ya consta la fecha de recepcion del proyecto en el expediente.',
                'mensaje_incumplida' => 'Todavia no existe fecha de recepcion del proyecto en el expediente.',
                'tipo' => DateRuleType::NOTIFICATION,
                'fase' => null,
                'estado' => null,
                'accion' => DateRuleAction::NOTIFY,
                'activa' => true,
                'operacion' => DateRuleOperation::BOTH,
                'plazo_dias' => null,
                'aviso_dias' => null,
                'connection_name' => 'Obras',
                'dispara_si_cumple' => true,
            ],
            [
                'nombre' => 'RECEPCION_PROVISIONAL_REGISTRADA',
                'descripcion' => 'Lanza una notificacion cuando ya consta fecha de recepcion provisional.',
                'tabla1' => 'ActasRecepcionObra',
                'tabla2' => null,
                'campo1' => 'Fecha_Acta_RecProv',
                'campo2' => null,
                'condicion' => DateRuleCondition::IS_DATE,
                'mensaje' => 'La recepcion provisional ha quedado registrada.',
                'mensaje_preventivo' => null,
                'mensaje_cumplida' => 'Ya consta la fecha de recepcion provisional de la obra.',
                'mensaje_incumplida' => 'Todavia no existe fecha de recepcion provisional en la obra.',
                'tipo' => DateRuleType::NOTIFICATION,
                'fase' => null,
                'estado' => null,
                'accion' => DateRuleAction::NOTIFY,
                'activa' => true,
                'operacion' => DateRuleOperation::BOTH,
                'plazo_dias' => null,
                'aviso_dias' => null,
                'connection_name' => 'Obras',
                'dispara_si_cumple' => true,
            ],
        ];

        foreach ($rules as $rule) {
            DateValidationRule::query()->updateOrCreate(
                ['nombre' => (string) $rule['nombre']],
                $rule,
            );
        }
    }
}
